test:
	@echo "[nosetests] running..."
	nosetests cw.py
	nosetests gw.py
	nosetests ks.py
	nosetests am.py
	nosetests eb.py
	@echo "[nosetests] done."
	@echo
	@echo "[doctest] running..."
	python -m doctest am.py
	@echo "[doctest] done."
